const PORT = process.env.PORT || 3000;
const express = require('express');
const app = express();
const http = require('http').Server(app);
const io = require('socket.io')(http);

// serve client-side files from ./public
app.use(express.static(__dirname + '/public'));

let clientInfo = {};

// socket.io listening for connection event
io.on('connection', (socket) => {
    console.log('User connected via socket.io!');
    socket.emit('message', {
        name: 'Sytem Message',
        text: 'Welcome to SocketChat',
        timestamp: new Date()
    });

    socket.on('joinRoom', (req) => {
        clientInfo[socket.id] = req; // socket.id is auto-generated by socket.io
        socket.join(req.room);
        socket.broadcast.to(req.room).emit('message', {
            name: 'System Message',
            text: req.name + ' has joined!',
            timestamp: new Date()
        })
    });
    
    socket.on('message', (message) => {
        console.log('Message received: ' + message.text);
        message.timestamp = new Date();
        io.to(clientInfo[socket.id].room).emit('message', message); // this will broadcast to all socket instances including this one.
        // socket.broadcast.emit('message', message); // this would broadcast to all other socket instances excluding this one.
    });

});

http.listen(PORT, () => {
    console.log('Server listening on PORT ' + PORT);
});